= Testando a Obtenção das Configurações do ConfigMap

== Minikube

Esse passo a passo assume que o ambiente docker, minikube e kubectl já esteja instalado.

* Construindo o projeto: `gradle clean build`
* Iniciando o minukube: `minikube start`
* Alterando o ambiente para o docker do minikube: `eval $(minikube docker-env)`
* Agora, com o contexto alterado, é necessário gerar as imagens:
** Gerando a imagem: `docker build -t demo-config-map:0.0.1 .`
* Adicionando o ConfigMap: `kubectl apply -f k8s/configMap.yml`
* Fazendo o deploy da aplicação: `kubectl apply -f k8s/appDeploy.yml`
* Para acessar as aplicações externamente, você deve executar o comando: `minikube tunnel`
* Em outro terminal, você pode executar o comando `kubectl get svc` para pegar o endereço externo da aplicação.
* Para realizar o teste, basta executar um *curl* para o endereço externo, no recurso `/config/{key_from_config_map}`, por exemplo: `curl 10.109.152.2:8080/config/config.test`
** Onde `10.109.152.2:8080` corresponde ao IP e a porta retornado no comando de lista dos serviços.